apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: request-reply
  namespace: knative-eventing
  labels:
    app.kubernetes.io/component: request-reply
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: knative-eventing
spec:
  replicas: 1
  selector:
    matchLabels:
      eventing.knative.dev/part-of: request-reply
  template:
    metadata:
      labels:
        eventing.knative.dev/part-of: request-reply
        app.kubernetes.io/component: request-reply
        app.kubernetes.io/version: devel
        app.kubernetes.io/name: knative-eventing
    spec:
      containers:
      - name: request-reply
        image: ko://knative.dev/eventing/cmd/requestreply
        volumeMounts:
          - name: aes-keys
            mountPath: /etc/secrets
        env:
          - name: SYSTEM_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_INDEX
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
          - name: HTTP_PORT
            value: "8080"
          - name: HTTPS_PORT
            value: "8443"
          - name: SECRETS_PATH
            value: "/etc/secrets"
          - name: CONFIG_LOGGING_NAME
            value: config-logging
          - name: CONFIG_OBSERVABILITY_NAME
            value: config-observability

        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP

      serviceAccountName: request-reply
      volumes:
        - name: aes-keys
          secret:
            secretName: request-reply-keys
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    eventing.knative.dev/part-of: request-reply
    app.kubernetes.io/component: request-reply
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: knative-eventing
  name: request-reply
  namespace: knative-eventing
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    eventing.knative.dev/part-of: request-reply
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    eventing.knative.dev/part-of: request-reply
    app.kubernetes.io/component: request-reply
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: knative-eventing
  name: request-reply-keys
  namespace: knative-eventing
